package com.ted.gartenhelferlein.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF356A22)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBDD0B0)
val md_theme_light_onPrimaryContainer = Color(0xFF2E332B)
val md_theme_light_secondary = Color(0xFF755B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDF91)
val md_theme_light_onSecondaryContainer = Color(0xFF241F14)
val md_theme_light_tertiary = Color(0xFFFAD8AA)
val md_theme_light_onTertiary = Color(0xFF110909)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onTertiaryContainer = Color(0xFF29231A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFD6E0AB)
val md_theme_light_onBackground = Color(0xFF1D1D1B)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF22251D)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDEB)
val md_theme_light_inverseSurface = Color(0xFF5F1416)
val md_theme_light_inversePrimary = Color(0xFF9AD680)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF356A22)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9AD680)
val md_theme_dark_onPrimary = Color(0xFF0C3900)
val md_theme_dark_primaryContainer = Color(0xFF1C520A)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0F7D6)
val md_theme_dark_secondary = Color(0xFFF0DDA9)
val md_theme_dark_onSecondary = Color(0xFF312500)
val md_theme_dark_secondaryContainer = Color(0xFF584F2F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDF91)
val md_theme_dark_tertiary = Color(0xFF291D0D)
val md_theme_dark_onTertiary = Color(0xFFEED7AF)
val md_theme_dark_tertiaryContainer = Color(0xFF292112)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D201D)
val md_theme_dark_onBackground = Color(0xFFE8FDAF)
val md_theme_dark_surface = Color(0xFF1A1917)
val md_theme_dark_onSurface = Color(0xFFDBD3D3)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF410005)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD7)
val md_theme_dark_inversePrimary = Color(0xFF356A22)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9AD680)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFBDD0B0)
